#!/usr/bin/env bash
set -euo pipefail

# Build markdown report from outdated actions.
# Input:  actions-outdated.txt (action|current_sha|current_tag|latest_sha|latest_tag)
# Output: outdated-actions-report.md

cat > outdated-actions-report.md << 'HEADER'
## Outdated GitHub Actions Detected

The following actions have newer versions available:

| Action | Current | Latest | Recommended Update |
|--------|---------|--------|-------------------|
HEADER

while IFS='|' read -r action current_sha current_tag latest_sha latest_tag; do
  echo "| \`${action}\` | ${current_tag:-${current_sha:0:7}} | ${latest_tag} | \`${action}@${latest_sha} # ${latest_tag}\` |" >> outdated-actions-report.md
done < actions-outdated.txt

cat >> outdated-actions-report.md << 'FOOTER'

### How to Update

Replace each action reference in your workflow files with the SHA-pinned version shown in the "Recommended Update" column.

### Why SHA Pinning?

Pinning to a commit SHA prevents supply chain attacks where a malicious actor could move a tag to point to compromised code.

---
*This issue was automatically generated by the [Check Action Versions](.github/workflows/check-action-versions.yml) workflow.*
FOOTER

echo "Report generated:"
cat outdated-actions-report.md
